include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    type_annotate_public_apis: false
    avoid_positional_boolean_parameters: false
    avoid_redundant_argument_values: false
    prefer_constructors_over_static_methods: false
analyzer:
  strong-mode:
    implicit-casts: true
  exclude:
    - "lib/features/inner_drawer_example/inner_drawer_custom.dart"
    - "lib/features/inner_drawer_example/inner_drawer_example_screen.dart"
